/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import javax.swing.JOptionPane;

/**
 *
 * @author D E R I
 */
public class GUI_TransaksiKafe extends javax.swing.JFrame {

public GUI_TransaksiKafe() {
        initComponents();
        
     txtNamaBarang.setEnabled(true); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chkMinuman = new javax.swing.JCheckBox();
        txtHarga = new javax.swing.JTextField();
        Jumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        chkMakanan = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transaksi Restaurant");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel2.setText("Nama Barang");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jLabel3.setText("Harga");

        chkMinuman.setText("Minuman");
        chkMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMinumanActionPerformed(evt);
            }
        });

        Jumlah.setText("Jumlah");

        chkMakanan.setText("Makanan");
        chkMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMakananActionPerformed(evt);
            }
        });

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chkMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1)))
                .addContainerGap(664, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkMakanan)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jumlah)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(chkMinuman)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMinumanActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_chkMinumanActionPerformed

    private void chkMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMakananActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String namaBarang = txtNamaBarang.getText();
    String hargaText = txtHarga.getText();
    String jumlahText = txtJumlah.getText();

    // Tambahkan exception jika data kosong
    if (namaBarang.isEmpty() || hargaText.isEmpty() || jumlahText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Keluar dari method
    }

    try {
        double harga = Double.parseDouble(hargaText);
        int jumlah = Integer.parseInt(jumlahText);

        TransaksiResto transaksi;
        String jenisProduk = ""; // Untuk menyimpan keterangan Makanan atau Minuman

        if (chkMakanan.isSelected() && !chkMinuman.isSelected()) {
            transaksi = new TransaksiRestoMakanan(namaBarang, harga, jumlah);
            jenisProduk = "Makanan";
        } else if (chkMinuman.isSelected() && !chkMakanan.isSelected()) {
            transaksi = new TransaksiRestoMinuman(namaBarang, harga, jumlah);
            jenisProduk = "Minuman";
        } else if (chkMakanan.isSelected() && chkMinuman.isSelected()) {
            // Tambahkan exception jika keduanya dicentang bersamaan
            JOptionPane.showMessageDialog(this, "Harus memilih hanya satu jenis produk (Makanan atau Minuman)!", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Keluar dari method
        } else {
            transaksi = new TransaksiResto(namaBarang, harga, jumlah);
        }

        txtOutput.setText("Transaksi Kafe\n");
        txtOutput.append("---------------\n");
        txtOutput.append("Jenis Produk: " + jenisProduk + "\n"); // Menampilkan keterangan Makanan atau Minuman
        txtOutput.append("Nama Barang: " + transaksi.getNamaBarang() + "\n");
        txtOutput.append("Harga per Unit: " + transaksi.getHarga() + "\n");
        txtOutput.append("Jumlah: " + transaksi.getJumlah() + "\n");
        txtOutput.append("Total Harga: " + transaksi.hitungTotal() + "\n");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format harga atau jumlah tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}




    

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TransaksiKafe().setVisible(true);
            }
        });    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jumlah;
    private javax.swing.JCheckBox chkMakanan;
    private javax.swing.JCheckBox chkMinuman;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
