/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import javax.swing.JOptionPane;

/**
 *
 * @author D E R I
 */
public class GUI_PesananMinum extends javax.swing.JFrame {

public GUI_PesananMinum() {
        initComponents();
        
     txtNamaBarang.setEnabled(true); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        Jumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        chkOnline = new javax.swing.JCheckBox();
        chkLangsung = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Stok Minuman");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 16));

        jLabel2.setText("Nama Minuman");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        jLabel3.setText("Harga");

        Jumlah.setText("Jumlah");

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkOnline.setText("Pesan Online ( disk 5% )");
        chkOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOnlineActionPerformed(evt);
            }
        });

        chkLangsung.setText("Pesan Langsung ( disk 10% )");
        chkLangsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLangsungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkLangsung)
                            .addComponent(chkOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1)))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jumlah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkOnline))))
                    .addComponent(chkLangsung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
        String namaBarang = txtNamaBarang.getText();

        // Validasi apakah field harga dan jumlah tidak kosong
        if (txtHarga.getText().isEmpty() || txtJumlah.getText().isEmpty()) {
            throw new Exception("Data tidak boleh kosong");
        }

        double harga = Double.parseDouble(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());

        TransaksiResto transaksi;
        String jenisProduk = ""; // Untuk menyimpan keterangan Makanan atau Minuman
        double diskon = 0; // Untuk menyimpan nilai diskon

        if (chkLangsung.isSelected() && !chkOnline.isSelected()) {
            transaksi = new TransaksiRestoMakanan(namaBarang, harga, jumlah);
            jenisProduk = "Makanan";
            diskon = 0.1; // Diskon 10% untuk Makanan
        } else if (chkOnline.isSelected() && !chkLangsung.isSelected()) {
            transaksi = new TransaksiRestoMinuman(namaBarang, harga, jumlah);
            jenisProduk = "Minuman";
            diskon = 0.05; // Diskon 5% untuk Minuman
        } else if (chkLangsung.isSelected() && chkOnline.isSelected()) {
            // Jika kedua checkbox dicentang bersamaan, hasilnya kosong
            txtOutput.setText("Transaksi Kafe\n");
            txtOutput.append("---------------\n");
            txtOutput.append("Pilih hanya satu jenis pemesanan (Langsung atau Online)\n");
            return; // Keluar dari method
        } else {
            transaksi = new TransaksiResto(namaBarang, harga, jumlah);
        }

        // Menghitung total harga dengan memperhitungkan diskon
        double totalHarga = transaksi.hitungTotal() * (1 - diskon);

        txtOutput.setText("Transaksi Kafe\n");
        txtOutput.append("---------------\n");
        txtOutput.append("Jenis Produk: " + jenisProduk + "\n"); // Menampilkan keterangan Makanan atau Minuman
        txtOutput.append("Nama Barang: " + transaksi.getNamaBarang() + "\n");
        txtOutput.append("Harga per Unit: " + transaksi.getHarga() + "\n");
        txtOutput.append("Jumlah: " + transaksi.getJumlah() + "\n");
        txtOutput.append("Total Harga (Setelah Diskon): " + totalHarga + "\n");

    } catch (NumberFormatException e) {
        // Tangani jika terjadi kesalahan konversi angka
        JOptionPane.showMessageDialog(null, "Format angka tidak valid", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Tangani jika terjadi kesalahan lainnya (misalnya, data kosong)
        JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOnlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOnlineActionPerformed

    private void chkLangsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLangsungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLangsungActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jumlah;
    private javax.swing.JCheckBox chkLangsung;
    private javax.swing.JCheckBox chkOnline;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
